config/routes.rb
Rails.application.routes.draw do
  resources :stocks
  devise_for :users
  # get 'home/index'
  root 'home#index'
  get 'home/about'

  post "/" => 'home#index'

  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/stock.rb
# in app/models/stocks.rb

class Stock < ApplicationRecord

	belongs_to :user
end

app/models/user.rb
# in app/models/user.rb

class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
         has_many :stocks

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/home_controller.rb
# app/controllers/home_controller.rb


class HomeController < ApplicationController
  def index
  	 @api = StockQuote::Stock.new(api_key: 'pk_b5e10db893cf4535989ff6874cf01189')
  	# <% StockQuote::Stock.new(api_key: 'pk_b5e10db893cf4535989ff6874cf01189') %>
	if params[:ticker] == ""
		@nothing = "*Enter a stock symbol*"
	elsif params[:ticker]
	  @stock = StockQuote::Stock.quote(params[:ticker]) 
	  if !@stock 
	  		 @error = "Stock symbol do not exist!"
	  end	
	end
  end

  def about
  end
  
end

app/controllers/stocks_controller.rb
# apps/controllers/stocks_controller.rb

class StocksController < ApplicationController
  before_action :set_stock, only: [:show, :edit, :update, :destroy]
  before_action :correct_user, only: [:edit, :update, :destroy]
  before_action :authenticate_user!


  # GET /stocks
  # GET /stocks.json
  def index
    @stocks = Stock.all
  end

  # GET /stocks/1
  # GET /stocks/1.json
  def show
  end

  # GET /stocks/new
  def new
    @stock = Stock.new
  end

  # GET /stocks/1/edit
  def edit
  end

  # POST /stocks
  # POST /stocks.json
  def create
    @stock = Stock.new(stock_params)

    respond_to do |format|
      if @stock.save
        format.html { redirect_to @stock, notice: 'Stock was successfully created.' }
        format.json { render :show, status: :created, location: @stock }
      else
        format.html { render :new }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /stocks/1
  # PATCH/PUT /stocks/1.json
  def update
    respond_to do |format|
      if @stock.update(stock_params)
        format.html { redirect_to @stock, notice: 'Stock was successfully updated.' }
        format.json { render :show, status: :ok, location: @stock }
      else
        format.html { render :edit }
        format.json { render json: @stock.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /stocks/1
  # DELETE /stocks/1.json
  def destroy
    @stock.destroy
    respond_to do |format|
      format.html { redirect_to stocks_url, notice: 'Stock was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  def correct_user 
    @ticker = correct_user.stocks.find_by(id: params[:id])
    redirect_to stocks_path, notice: "Not Authorized to edit this stock" if @ticker.nil?
  end   
    


  private
    # Use callbacks to share common setup or constraints between actions.
    def set_stock
      @stock = Stock.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def stock_params
      params.require(:stock).permit(:ticker, :user_id)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/stocks_helper.rb
module StocksHelper
end

app/views/home/_flash.html.erb
<!-- apps/views/home/_flash.html.erb     -->
 
 <br/>
 <% flash.each do |name, msg| %>
 	<div class="alert alert-success alert-dismissable" role="alert">
 		<button class="close" data-dismiss="alert"> 
 			<small><sup>x</sup></small>
 		</button>
 		 <%= content_tag(:div, msg) %>
  	</div>
 <% end %>

app/views/home/_footer.html.erb
<br/><br/><br/><br/>
<center>Copyright (c) Bill Leezer</center>

app/views/home/_navbar.html.erb
<!-- in apps/views/home/_navbar.html.erd  -->


<nav class="navbar navbar-expand-lg navbar-light bg-light">
	<%= link_to "Stocking Market", root_path, class: "navbar-brand" %>

	<button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">

      <li class="nav-item">
      	<%= link_to "About",home_about_path, class: "nav-link" %>
      </li>

      <% if user_signed_in? %>
        <li class="nav-item">
        <%= link_to "Edit Profile", edit_user_registration_path, class: "nav-link" %>
        </li>
         <li class="nav-item">
        <%= link_to "Show Stocks", stocks_path, class: "nav-link" %>
        </li>
         <li class="nav-item">
        <%= link_to "Add Stocks", new_stock_path, class: "nav-link" %>
        </li>


        <li class="nav-item">
          <%= link_to "Log Out", destroy_user_session_path, method: :delete, class: "nav-link" %>
        </li>
      <% else %>  
        <li class="nav-item">
          <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
        </li>
        <li class="nav-item">
          <%= link_to "Login",  new_user_session_path, class: "nav-link" %>
        </li>
      <% end %>  

            
    </ul>
    <form class="form-inline my-2 my-lg-0">
      <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search">
      <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>

    </form>
  </div></nav>

app/views/home/about.html.erb
<h1>About ME</h1>
<p>Hello, My name is Bill Leezer in a class by John Elder at Codemy.com</p>

app/views/home/index.html.erb
<!--  in app/views/home/index>html.erb  -->

<h1>Stocking</h1>
<!-- <p>Hello, this is my first rails App!</p>
     <p>Find me in app/views/home/index.html.erb</p>  -->

<!-- Form Tag -->  
<%= form_tag root_path, :method => 'POST' do %>
	<%= text_field_tag 'ticker', nil, placeholder: "Enter Ticker Symbol", size: 50 %>
	<%= submit_tag 'Lookup' %>
<% end %>

<br/>

<% if @stock %>
	<img src="<%= @stock.url %>"> <br/><br/>
	<%= @stock.company_name %><br/><br/>
	$<%= @stock.latest_price %><br/><br/>
<% elsif @nothing %>
	<%= @nothing %>
<% end %>

<% if @error %>
	<%= @error %>
<% end %>

app/views/layouts/application.html.erb
<!--  app/views/layouts/application.html.erb   -->

<!DOCTYPE html>
<html>
  <head>
    <title>Stock Market App</title>

    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">

    <%= csrf_meta_tags %>

    <%= stylesheet_link_tag  'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
	<%=  render 'home/navbar' %>

	<div class="container">
    <%= render 'home/flash' %>
   
    <br/>
    	<%= yield %>
    </div>

    <%=  render 'home/footer' %>

  </body>
</html>

app/views/stocks/_form.html.erb
<!--  in app/views/stocks/form.html.erb  -->


<%= form_with(model: stock, local: true) do |form| %>
  <% if stock.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(stock.errors.count, "error") %> prohibited this stock from being saved:</h2>

      <ul>
      <% stock.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :ticker %>
    <%= form.text_field :ticker, id: :stock_ticker %>
  </div>

  <div class="field">
    <%= form.number_field :user_id, id: :stock_user_id, value: current_user.id, type: :hidden %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/stocks/edit.html.erb
<h1>Editing Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Show', @stock %> |
<%= link_to 'Back', stocks_path %>

app/views/stocks/index.html.erb
<!--  in app/views/stocks/index.html.erb  -->

<h1>Stocks</h1>

<table>
  <thead>
    <tr>
      <th>Ticker</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @stocks.each do |stock| %>
    <% if stock.user_id == current_user.id %>
      <tr>
        <td><%= stock.ticker %></td>
        <td><%= stock.user_id %></td>
        <td><%= link_to 'Show', stock %></td>
        <td><%= link_to 'Edit', edit_stock_path(stock) %></td>
        <td><%= link_to 'Destroy', stock, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %> 
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Stock', new_stock_path %>

app/views/stocks/new.html.erb
<h1>New Stock</h1>

<%= render 'form', stock: @stock %>

<%= link_to 'Back', stocks_path %>

app/views/stocks/show.html.erb
<!--  in app/views/stocks/show.html.erb  -->

<p>
  <strong>Ticker:</strong>
  <%= @stock.ticker %>
</p>

<!--
<p>
  <strong>User:</strong>
  <%= @stock.user_id %>
</p>
-->

<%= link_to 'Edit', edit_stock_path(@stock) %> |
<%= link_to 'Back', stocks_path %>